# Generated by Django 3.1.3 on 2020-11-22 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_hosting.abstractcontent_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AbstractFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_hosting.abstractfile_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('abstractfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hosting.abstractfile')),
                ('bitrate', models.PositiveSmallIntegerField(verbose_name='Bitrate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hosting.abstractfile',),
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('abstractcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hosting.abstractcontent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hosting.abstractcontent',),
        ),
        migrations.CreateModel(
            name='SubtitleFile',
            fields=[
                ('abstractfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hosting.abstractfile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hosting.abstractfile',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('abstractcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hosting.abstractcontent')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hosting.abstractcontent',),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('abstractfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hosting.abstractfile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hosting.abstractfile',),
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(verbose_name="Attachment's Position")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hosting.abstractcontent', verbose_name='Content')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hosting.post', verbose_name='Post')),
            ],
        ),
        migrations.AddField(
            model_name='abstractcontent',
            name='posts',
            field=models.ManyToManyField(related_name='attachments', through='hosting.PostContent', to='hosting.Post', verbose_name='Where It Is Used'),
        ),
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('filecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hosting.filecontent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hosting.filecontent',),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('filecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hosting.filecontent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('hosting.filecontent',),
        ),
        migrations.AddField(
            model_name='abstractfile',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hosting.filecontent', verbose_name='Content using thisFile'),
        ),
    ]
