# Generated by Django 3.1.3 on 2020-12-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20201201_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_contents', to='hosting.post', verbose_name='Post'),
        ),
    ]
