"""
Django settings for jw_test project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
import yaml

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def place_relative_path_to_base_dir(path: str) -> str:
    if not os.path.isabs(path):
        path = os.path.abspath(os.path.join(
            BASE_DIR,
            path,
        ))
    return path

DEMO_SECRET_KEY = 'jw-test-demo-secret-key'

default_settings = {
    # customization
    'DATE_FORMAT': '%Y-%m-%d',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M',
    'POST_PREVIEW_LEN': 30,
    'POST_PREVIEW_TRAILING': '<...>',
    'REST_PAGE_SIZE': 50,

    # security
    'SECRET_KEY': DEMO_SECRET_KEY,
    'DEBUG': True,
    'ALLOWED_HOSTS': [
        '127.0.0.1',
        'localhost',
    ],

    # databases
    'DEFAULT_DB_ENGINE': 'django.db.backends.postgresql_psycopg2',
    'DEFAULT_DB_NAME': 'jw_test_db',
    'DEFAULT_DB_HOST': 'demo-db',
    'DEFAULT_DB_PORT': 5432,
    'DEFAULT_DB_USER': 'demo',
    'DEFAULT_DB_PASSWORD': 'demo',
    'DEFAULT_TEST_DB_NAME': 'jw_test_db',

    # static
    'MEDIA_ROOT': './media',
    'MEDIA_URL': '/media/',
    'STATIC_ROOT': './static',
    'STATIC_URL': '/static/',

    # internationalization
    'LANGUAGE_CODE': 'en-us',
    'TIME_ZONE': 'Europe/Volgograd',
    'USE_I18N': True,
    'USE_L10N': True,
    'USE_TZ': True,

    # caches
    'DEFAULT_CACHE_BACKEND': 'django.core.cache.backends.db.DatabaseCache',
    'DEFAULT_CACHE_LOCATION': 'django_cache_table',

    # celery
    'CELERY_RESULT_BACKEND': 'django-db',
    'CELERY_CACHE_BACKEND': 'default',
    'CELERY_RESULT_PERSISTENT': False,
    'BROKER_URL': 'amqp://guest:guest@rabbit:5672//',
}

globals().update({
    var: os.getenv(var, default_value)
    for var, default_value in default_settings.items()
})
if SECRET_KEY == DEMO_SECRET_KEY:
    print(
        'SECRET_KEY is not provided! DEMO_SECRET_KEY is used instead',
        file=sys.stderr,
    )

CACHES = {
    'default': dict(
        BACKEND=DEFAULT_CACHE_BACKEND,
        LOCATION=DEFAULT_CACHE_LOCATION,
    ),
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': REST_PAGE_SIZE,
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party apps
    'rest_framework',
    'polymorphic',
    'django_celery_results',

    # local apps
    'hosting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jw_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jw_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': dict(
        ENGINE=DEFAULT_DB_ENGINE,
        NAME=DEFAULT_DB_NAME,
        HOST=DEFAULT_DB_HOST,
        PORT=DEFAULT_DB_PORT,
        USER=DEFAULT_DB_USER,
        PASSWORD=DEFAULT_DB_PASSWORD,
        TEST={
            'NAME': DEFAULT_TEST_DB_NAME,
        },
    ),
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = place_relative_path_to_base_dir(
    path=STATIC_ROOT,
)

MEDIA_ROOT = Path(place_relative_path_to_base_dir(
    path=MEDIA_ROOT,
))
MEDIA_ROOT.mkdir(
    mode=0o755,
    parents=True,
    exist_ok=True,
)
